server:
  port: 8080

# we enable some of the management endpoints to make it possible to restart the application
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
